import unittest
from test_math import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()
    tests = [TestMathFunc("test_add"), TestMathFunc(
        "test_minus"), TestMathFunc("test_divide")]
    tests2 = [TestMathFunc("test_minus"), TestMathFunc(
        "test_add"), TestMathFunc("test_divide")]
    suite.addTests(tests)
    suite.addTests(tests2)

    # # 1-直接用addTest方法添加单个TestCase
    # suite.addTest(TestMathFunc("test_multi"))
    # # 2-用addTests + TestLoader，loadTestsFromName()，传入'模块名.TestCase名'
    # suite.addTests(unittest.TestLoader().loadTestsFromName('test_math.TestMathFunc'))
    # # 3-类似，传入列表
    # suite.addTests(unittest.TestLoader().loadTestsFromNames(['test_math.TestMathFunc']))  # loadTestsFromNames()
    # # 4-loadTestsFromTestCase()，传入TestCase
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # # 输出保存测试结果
    # with open('UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    # 以HTML输出测试结果
    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
